const fs = require('fs');
const path = require('path');
const { getIndex } = require('../../scripts/utils/collections-index');

// Card list for the collections explore page, ordered non-featured before
// featured (user's call): auto tag collections first, then curated
// non-featured, then curated featured.
//
// Counts are computed at build wherever a config's matchBy exists — including
// configs still shadowed by a legacy static page (the rule is the same even
// when the page is hand-built). Registry entries with no config (richard-prince,
// magazines) fall back to their registry bookCount until those pages migrate.
module.exports = function() {
  const { pages, curated: configs, defaultWing } = getIndex();

  const registry = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'libraryCollections.json'), 'utf8')
  ).collections;

  const configBySlug = new Map(configs.map(cfg => [cfg.slug, cfg]));

  const curated = registry.map(entry => {
    const cfg = configBySlug.get(entry.slug);
    return { ...entry, bookCount: cfg ? cfg.bookCount : entry.bookCount };
  });

  // This page is the art wing's collections index; other wings list their own
  // on their landing page (Phase 2.B).
  const tagTier = pages
    .filter(c => c.autoGenerated && c.wing === defaultWing)
    .map(c => ({
      id: c.slug,
      name: c.title,
      slug: c.slug,
      description: c.description,
      category: 'subject',
      featured: false,
      image: c.image,
      path: `/${c.permalink}`,
      bookCount: c.bookCount,
    }));

  return [
    ...tagTier,
    ...curated.filter(c => !c.featured),
    ...curated.filter(c => c.featured),
  ];
};
