const fs = require('fs');
const path = require('path');
const CSVHandler = require('../../scripts/utils/csv-handler');
const { matchesCollection } = require('../../scripts/utils/collection-matcher');
const collectionConfigs = require('./collectionConfigs');

// Card list for the collections explore page, ordered non-featured before
// featured (user's call): auto tag collections first, then curated
// non-featured, then curated featured.
//
// Counts are computed at build wherever a config's matchBy exists — including
// configs still shadowed by a legacy static page (the rule is the same even
// when the page is hand-built). Registry entries with no config (richard-prince,
// magazines) fall back to their registry bookCount until those pages migrate.
module.exports = function() {
  let books = [];
  try {
    books = CSVHandler.readBooksSync(path.join(__dirname, 'books.csv')).data;
  } catch (err) {
    console.error('exploreCollections: could not read books.csv:', err.message);
  }

  const registry = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'libraryCollections.json'), 'utf8')
  ).collections;

  const configDir = path.join(__dirname, 'collections');
  const configBySlug = new Map(
    fs.readdirSync(configDir)
      .filter(f => f.endsWith('.json'))
      .map(f => JSON.parse(fs.readFileSync(path.join(configDir, f), 'utf8')))
      .map(cfg => [cfg.slug, cfg])
  );

  const curated = registry.map(entry => {
    const cfg = configBySlug.get(entry.slug);
    return {
      ...entry,
      bookCount: cfg
        ? books.filter(b => matchesCollection(b, cfg)).length
        : entry.bookCount,
    };
  });

  const tagTier = collectionConfigs()
    .filter(c => c.autoGenerated)
    .map(c => ({
      id: c.slug,
      name: c.title,
      slug: c.slug,
      description: c.description,
      category: 'subject',
      featured: false,
      image: c.image,
      path: `/collections/${c.slug}.html`,
      bookCount: c.bookCount,
    }));

  return [
    ...tagTier,
    ...curated.filter(c => !c.featured),
    ...curated.filter(c => c.featured),
  ];
};
